### ISSUE TITLE
SvelteKit: <ProgressBar> is not a valid SSR component.

### ISSUE THREAD

**Issue by TimoReusch** [okrad/svelte-progressbar#30]
I get this error when trying to use the lib with SvelteKit, while Svelte works fine.

```
<ProgressBar> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
Error: <ProgressBar> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Module.validate_component (/node_modules/svelte/internal/index.mjs:1748:15)
    at eval (/src/lib/components/CircularProgress.svelte:33:58)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1771:22)
    at ProjectCard.svelte:22:20
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1771:22)
    at Object.default (/src/routes/app/projects/+page.svelte:15:101)
    at eval (/src/lib/components/Container.svelte:30:36)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1771:22)
    at eval (/src/routes/app/projects/+page.svelte:13:97)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1771:22)
```

**Comment by okrad** [comment]
Hi @TimoReusch, can you try with the current release?
Thank you!
